ARG FROM

FROM ${FROM}

RUN apk update && apk add --no-cache supervisor

COPY --from=cors_supervisord /etc/supervisor/ /etc/supervisor/

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
