ARG FROM

FROM ${FROM} AS cors_supervisord

RUN apk update && apk add --no-cache supervisor

COPY supervisord/supervisord.conf /etc/supervisor/supervisord.conf
COPY supervisord/pimcore.conf /etc/supervisor/conf.d/pimcore.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
