ARG FROM

FROM ${FROM}

RUN set -eux; \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers; \
    pecl install xdebug; \
    docker-php-ext-enable xdebug; \
    apk del --no-network .build-deps; \
    rm -rf /tmp/pear /tmp/* /var/cache/apk/*

COPY --chmod=755 php/docker-xdebug-entrypoint.sh /usr/local/bin/xdebug-entrypoint

ENTRYPOINT ["xdebug-entrypoint"]
CMD ["php-fpm"]
