ARG FROM

FROM ${FROM}

RUN apk add --no-cache \
      apk-tools autoconf gcc make g++ automake nasm ninja cmake clang clang-dev; \
    pecl install xdebug-3.2.2; \
    docker-php-ext-enable xdebug; \
    apk del autoconf gcc make g++ automake nasm ninja cmake clang clang-dev; \
    rm -rf /var/cache/apk/*;

COPY php/docker-xdebug-entrypoint.sh /usr/local/bin/xdebug-entrypoint

RUN chmod +x /usr/local/bin/xdebug-entrypoint

ENTRYPOINT ["xdebug-entrypoint"]
CMD ["php-fpm"]
