name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      matrix:
        required: true
        type: string
      matrix_manifest:
        required: true
        type: string

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  IMAGICK_VERSION_FROM_SRC: 28f27044e435a2b203e32675e942eb8de620ee58

jobs:
  build:
    name: >
      Build ${{ inputs.component }}
      ${{ matrix.arch }}/${{ matrix.php_version || matrix.nginx_version }}${{ matrix.php_type && '/' }}${{ matrix.php_type || '' }}${{ matrix.alpine && '/' }}${{ matrix.alpine || '' }}
    runs-on: ${{ matrix.arch == 'amd' && 'ubuntu-22.04' || 'ubuntu-22.04-arm' }}
    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Name
        id: image_name
        run: |
          FROM_IMAGE=""
          
          if [ "${{ inputs.component }}" == "php" ]; then
            IMAGE_NAME=${{ matrix.arch }}-php-${{ matrix.php_type }}
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "php-debug" ]; then
            IMAGE_NAME=${{ matrix.arch }}-php-${{ matrix.php_type }}-debug
            FROM_IMAGE=ghcr.io/${{ github.repository }}/${{ matrix.arch }}-php-${{ matrix.php_type }}:${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "php-blackfire" ]; then
            IMAGE_NAME=${{ matrix.arch }}-php-${{ matrix.alpine }}-fpm-blackfire
            FROM_IMAGE=ghcr.io/${{ github.repository }}/${{ matrix.arch }}-php-fpm:${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "supervisord" ]; then
            IMAGE_NAME=${{ matrix.arch }}-php-supervisord
            FROM_IMAGE=ghcr.io/${{ github.repository }}/${{ matrix.arch }}-php-cli:${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "nginx" ]; then
            IMAGE_NAME=${{ matrix.arch }}-nginx
            IMAGE_TAG=${{ matrix.nginx_version }}-LATEST
          fi
          
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "FROM_IMAGE=$FROM_IMAGE" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Pull Latest Image for Cache
        run: |
          REGISTRY=ghcr.io/${{ github.repository }}
          docker pull $REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }} || echo "No cache available"

      - name: Build Docker Image
        id: build
        run: |
          DOCKERFILE=Dockerfile

          if [ "${{ inputs.component }}" == "php-debug" ]; then
            DOCKERFILE=Dockerfile-debug
          elif [ "${{ inputs.component }}" == "php-blackfire" ]; then
            DOCKERFILE=Dockerfile-blackfire
          elif [ "${{ inputs.component }}" == "supervisord" ]; then
            DOCKERFILE=Dockerfile-supervisord
          elif [ "${{ inputs.component }}" == "nginx" ]; then
            DOCKERFILE=Dockerfile-nginx
          fi

          REGISTRY=ghcr.io/${{ github.repository }}

          docker build \
            -f $DOCKERFILE \
            --tag $REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }} 
            --build-arg PHP_VERSION=${{ matrix.php_version || '' }} \
            $(if [ -n "${{ env.FROM_IMAGE }}" ]; then echo "--build-arg FROM=${{ env.FROM_IMAGE }}"; fi) \
            --build-arg PHP_TYPE=${{ matrix.php_type || '' }} \
            --build-arg ALPINE_VERSION=${{ matrix.alpine || '' }} \
            --build-arg IMAGICK_VERSION_FROM_SRC=${{ env.IMAGICK_VERSION_FROM_SRC || '' }} \
            --build-arg NGINX_VERSION=${{ matrix.nginx_version || '' }} .

      - name: Push Docker Image
        id: push
        run: |
            docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ matrix.php_version || matrix.nginx_version }}-LATEST

      - name: Get Image Digest
        id: get_digest
        run: |
          REGISTRY=ghcr.io/${{ github.repository }}
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $REGISTRY/$IMAGE_NAME:${{ matrix.php_version || matrix.nginx_version }}-LATEST | cut -d '@' -f 2)
          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_ENV
          echo "IMAGE_DIGEST=$DIGEST" # Output to logs for debugging

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ env.IMAGE_DIGEST }}
          push-to-registry: true

  manifest:
    name:
      Manifest
      ${{ inputs.component }}
      ${{ matrix.php_version || matrix.nginx_version }}${{ matrix.php_type && '/' }}${{ matrix.php_type || '' }}${{ matrix.alpine && '/' }}${{ matrix.alpine || '' }}
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJson(inputs.matrix_manifest) }}
    steps:
      - name: Login to GitHub Container Registry
        if: ${{ matrix.arch == 'amd' }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create and Push Multi-Arch Manifest
        if: ${{ matrix.arch == 'amd' }}
        run: |
          REGISTRY=ghcr.io/${{ github.repository }}

          if [ "${{ inputs.component }}" == "php" ]; then
            IMAGE_NAME=php-${{ matrix.php_type }}
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "php-debug" ]; then
            IMAGE_NAME=php-${{ matrix.php_type }}-debug
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "php-blackfire" ]; then
            IMAGE_NAME=${{ matrix.alpine }}-php-fpm-blackfire
            FROM_IMAGE=ghcr.io/${{ github.repository }}/${{ matrix.arch }}-php-fpm:${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "supervisord" ]; then
            IMAGE_NAME=php-supervisord
            IMAGE_TAG=${{ matrix.php_version }}-alpine${{ matrix.alpine }}-LATEST
          elif [ "${{ inputs.component }}" == "nginx" ]; then
            IMAGE_NAME=nginx
            IMAGE_TAG=${{ matrix.nginx_version }}-LATEST
          fi
          
          docker manifest create \
            $REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
            --amend $REGISTRY/amd-$IMAGE_NAME:$IMAGE_TAG \
            --amend $REGISTRY/arm-$IMAGE_NAME:$IMAGE_TAG
          
          docker manifest push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG