name: CORS Pimcore Docker Build

on:
  push:
    branches:
      - "7.0" 
    tags:
      - "*"
  workflow_dispatch: ~
  schedule:
    - cron: "0 2 * * *"

jobs:
  build_php:
    uses: ./.github/workflows/docker-build.yml
    with:
      component: php
      matrix: |
        {
          "arch": ["amd", "arm"],
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "php_type": ["fpm", "cli"],
          "alpine": ["3.20", "3.21"]
        }
      matrix_manifest: |
        {
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "php_type": ["fpm", "cli"],
          "alpine": ["3.20", "3.21"]
        }
      release_tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}-LATEST', github.ref_name) }}

  build_php_debug:
    uses: ./.github/workflows/docker-build.yml
    needs: build_php
    with:
      component: php-debug
      matrix: |
        {
          "arch": ["amd", "arm"],
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "php_type": ["fpm"],
          "alpine": ["3.20", "3.21"]
        }
      matrix_manifest: |
        {
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "php_type": ["fpm"],
          "alpine": ["3.20", "3.21"]
        }
      release_tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}-LATEST', github.ref_name) }}

  build_php_blackfire:
    uses: ./.github/workflows/docker-build.yml
    needs: build_php
    with:
      component: php-blackfire
      matrix: |
        {
          "arch": ["amd", "arm"],
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "alpine": ["3.20", "3.21"]
        }
      matrix_manifest: |
        {
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "alpine": ["3.20", "3.21"]
        }
      release_tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}-LATEST', github.ref_name) }}

  build_supervisord:
    uses: ./.github/workflows/docker-build.yml
    needs: build_php
    with:
      component: supervisord
      matrix: |
        {
          "arch": ["amd", "arm"],
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "alpine": ["3.20", "3.21"]
        }
      matrix_manifest: |
        {
          "php_version": ["8.1", "8.2", "8.3", "8.4"],
          "alpine": ["3.20", "3.21"]
        }
      release_tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}-LATEST', github.ref_name) }}

  build_nginx:
    uses: ./.github/workflows/docker-build.yml
    with:
      component: nginx
      matrix: |
        {
          "arch": ["amd", "arm"],
          "nginx_version": ["1.25", "1.26"]
        }
      matrix_manifest: |
        {
          "nginx_version": ["1.25", "1.26"]
        }
      release_tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}-LATEST', github.ref_name) }}